name: Bump formulae on schedule or request

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/autobump.yml
  workflow_dispatch:
    inputs:
      formulae:
        description: Custom list of formulae to livecheck and bump if outdated
        required: false
  schedule:
    # Every 3 hours with an offset of 15 minutes
    - cron: "15 */3 * * *"

permissions:
  contents: read

jobs:
  autobump:
    runs-on: ubuntu-22.04
    steps:
    - name: Update Homebrew formula
      uses: dawidd6/action-homebrew-bump-formula@v4
      env:
        HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
      with:
        token: ${{ secrets.HOMEBREW_TOKEN }}
        tap: ${{ github.repository }}
        livecheck: true

    - name: Delete old workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 14